version: '2'
volumes:
    sense-data:
services:
    connector:
        image: balenablocks/connector:raspberrypi3
        restart: always
        labels:
          io.balena.features.balena-api: '1'
        privileged: true
        environment: 
          - 'ENABLE_EXTERNAL_HTTP_LISTENER=1'
        ports:
          - "8080"
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'HOME_DASHBOARD_UID=balenaSense'
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    volumes:
      - 'sense-data:/data'
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
    dashboard:
        image: balenablocks/dashboard:raspberrypi3
        restart: always
        ports:
            - "80"
        volumes:
            - 'dashboard:/data'
